# Try/Except
## Error
我們來看看以下的範例:
```python
def dividedBy(dividend, divisor):
    return dividend / divisor


a = int(input('被除數是'))
b = int(input('除數是'))
print('結果是' + str(dividedBy(a, b)))
```

如果我們輸入正確的數字，當然會進行正確的除法計算，但是如果我們使用的除數是0，那會發生什麼事呢？

我們會看到：
> Traceback (most recent call last):  
     File "<string>", line 6, in <module>  
     File "<string>", line 2, in dividedBy  
   ZeroDivisionError: division by zero

ZeroDivisionError就是一個python直譯器直接報錯誤(Error)的方式。

## 例外處理
如果我們想要在程式中處理錯誤，那麼我們要使用例外處理。
我們來看看修改後的範例:
```python
def dividedBy(dividend, divisor):
    try:
        return dividend / divisor
    except ZeroDivisionError:
        print('您使用的除數是0喔~')


a = int(input('a='))
b = int(input('b='))
print('a/b結果=' + str(dividedBy(a, b)))
```

然後再試著執行看看。